question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from the moon.", "answer": "False"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "Goldfish have a memory of three seconds.", "answer": "False"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Wombat poop is cube-shaped.", "answer": "True"},
    {"text": "If you sneeze too hard, you can fracture a rib.", "answer": "True"},
    {"text": "The atomic symbol for tin is 'Ti'.", "answer": "False"},
    {"text": "The Mona Lisa has no eyebrows.", "answer": "True"},
    {"text": "Coca-Cola was originally green.", "answer": "False"},
    {"text": "Your ears and nose never stop growing.", "answer": "True"},
    {"text": "A bolt of lightning is five times hotter than the surface of the sun.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The first item sold on eBay was a broken laser pointer.", "answer": "True"},
    {"text": "There is no sound in space.", "answer": "True"},
    {"text": "The shortest war in history lasted only 38 minutes.", "answer": "True"},
    {"text": "Cleopatra was of Greek descent.", "answer": "True"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"}
]
